version: "3.7"

services:
  app:
    build:
      args:
        user: joaop
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: teste-multti
    container_name: teste-multti-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - multti

  db:
    image: mysql:8
    container_name: teste-multti-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    # ports:
    #   - "3306:3306"
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    networks:
      - multti

  phpmyadmin:
    image: phpmyadmin
    container_name: teste-multti-phpmyadmin
    environment:
      # PMA_HOST: db
      # PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - multti

  nginx:
    image: nginx:alpine
    container_name: teste-multti-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - multti

networks:
  multti:
    driver: bridge